# listen: :443

acme:
  domains:
    - senator.giize.com
  email: pm12.kusakin@gmail.com

auth:
  type: password
  password: algFNdE82VhJulMxov+JMdg5

masquerade:
  type: file
  file:
    dir: /var/www/html
    index: index.html

obfs:
  type: salamander
  salamander:
    password: Zpov2bBbv7h916kp2/z2Cw==