# listen: :443

acme:
  domains:
    - senator.giize.com
  email: pm12.kusakin@gmail.com

auth:
  type: password
  password: algFNdE82VhJulMxov+JMdg5

masquerade:
  type: proxy
  proxy:
    url: https://ria.ru
    rewriteHost: true

obfs:
  type: salamander
  salamander:
    password: Zpov2bBbv7h916kp2/z2Cw==