acme:
  domains:
    - senator.giize.com
  email: pm12.kusakin@gmail.com

auth:
  type: password
  password: algFNdE82VhJulMxov+JMdg5

masquerade:
  type: proxy
  proxy:
    url: https://www.ria.ru
    rewriteHost: true

ignoreClientBandwidth: true

resolver:
  type: udp
  udp:
    addr: 1.1.1.1:53
    timeout: 4s