acme:
  domains:
  - senator.giize.com
  email: pm12.kusakin@gmail.com
auth:
  type: password
  password:
  - Bqm3qjWDQLIEwEZpBNi68nC/O1bnTkgj
  - AIFtcUsd57Bec04AS9FQs5Lbivfo5Hod
  - Z2UPD4q9nLZTACytSRVG/9gJeDW/VFCy
  - PDItoyF+6snmeu+P3A/zammVkQ/m0lyD
  - pzxL7jPNPXzxw2K4WOwj29v2pUZ9R7Va
  - tfKj9RgR825xpiLHkVNq4Ss5H3CNgh5l
masquerade:
  proxy:
    rewriteHost: true
    url: https://www.github.com
  type: proxy
