name: Deploy (masquerade)
on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy Masquerade
    runs-on: ubuntu-latest
    steps:
    - name: Deliver to vps (masquerade)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        script: |
          cd /root/doomsday-vpn
          BRANCH="${{ github.ref_name }}"
          echo "Deploying branch (selected in UI): $BRANCH"
          git fetch origin
          git checkout "$BRANCH"
          git pull origin "$BRANCH"
          bash ./scripts/copy-config-masquerade.sh

    - name: Start py-bot and update config
      run: | 
            cd /root/doomsday-vpn/py-bot
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python update-config.py
            python bot.py

